plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'idea'
}

version = project.mod_version
group = project.maven_group

repositories {
}

// Fabric Loom Split Sourceset Yapılandırması
loom {
	splitEnvironmentSourceSets()

	mods {
		"gst" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

// IntelliJ IDEA'nın kaynak klasörleri (main ve client) doğru indekslemesini sağlayan blok
sourceSets {
	main {
		java { srcDirs = ['src/main/java'] }
		resources { srcDirs = ['src/main/resources'] }
	}
	client {
		java { srcDirs = ['src/client/java'] }
		resources { srcDirs = ['src/client/resources'] }

		// Client modülü Main'in ve Minecraft'ın tüm bağımlılıklarını okuyabilsin
		compileClasspath += main.compileClasspath + main.output
		runtimeClasspath += main.runtimeClasspath + main.output
	}
}

idea {
	module {
		sourceDirs += file('src/main/java')
		sourceDirs += file('src/client/java')
		resourceDirs += file('src/main/resources')
		resourceDirs += file('src/client/resources')

		// Client bağımlılıklarının IntelliJ kütüphane haritasına işlenmesi
		scopes.COMPILE.plus += [configurations.clientCompileClasspath]
		scopes.PROVIDED.plus += [configurations.clientCompileClasspath]
		scopes.RUNTIME.plus += [configurations.clientRuntimeClasspath]

		downloadJavadoc = false
		downloadSources = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName" }
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}